const date = {
    products:[
        {
            _id:'1',
            name:'Aluminum',
            category:'Household',
            image: '/images/8-round-aluminium-foil-food-container-1525.jpg',
            price:3.40,
            brand:'farla',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'2',
            name:'Aluminum',
            category:'Household',
            image:'/images/8-round-aluminium-foil-food-container-1525.jpg',
            price:3.40,
            brand:'farla',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'3',
            name:'Aluminum',
            category:'Household',
            image:'/images/8-round-aluminium-foil-food-container-1525.jpg',
            price:3.40,
            brand:'farla',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'4',
            name:'Aluminum',
            category:'Household',
            image:'/images/8-round-aluminium-foil-food-container-1525.jpg',
            price:3.40,
            brand:'farla',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'5',
            name:'Aluminum',
            category:'Household',
            image:'/images/8-round-aluminium-foil-food-container-1525.jpg',
            price:3.40,
            brand:'farla',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'6',
            name:'Aluminum',
            category:'Household',
            image:'/images/8-round-aluminium-foil-food-container-1525.jpg',
            price:3.40,
            brand:'farla',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'7',
            name:'Aluminum',
            category:'Household',
            image:'/images/8-round-aluminium-foil-food-container-1525.jpg',
            price:3.40,
            brand:'farla',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
        {
            _id:'8',
            name:'Aluminum',
            category:'Household',
            image:'/images/8-round-aluminium-foil-food-container-1525.jpg',
            price:3.40,
            brand:'farla',
            rating:4.5,
            numReviews:10,
            description:'high quality product',
        },
    ]
}
export default date;